Add release checklist
OpenFreeEnergy/openfe pull request #1007
Opened 2024-11-07 23:15 UTC by atravitz

Checklist
* [ ] Added a ``news`` entry

## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT License [here](https://github.com/OpenFreeEnergy/openfe/blob/main/LICENSE) and the **Developer Certificate of Origin** at <https://developercertificate.org/>.

2024-11-08 06:57 UTC, IAlibay approved these changes

2024-11-08 08:49 UTC, IAlibay requested changes
What about adding the conda lock and single file installers to the release assets?

2024-11-08 17:11 UTC, mikemhenry commented
That step happens after the conda-forge build is done/uploaded. Adding the assets is automated now 😎 but still requires a manual click to fire off (for now, we could automate it as well). So something like "After the conda-forge package is uploaded, start single file installer and docker image workflow (and verify it was successful)"

2024-11-12 20:07 UTC, IAlibay requested changes

2024-11-12 20:07 UTC, IAlibay commented on .github/PULL_REQUEST_TEMPLATE/release_template.md
> +After Merging the PR [follow this guide]https://github.com/OpenFreeEnergy/openfe/releases/new
```suggestion
After Merging the PR [follow this guide](https://github.com/OpenFreeEnergy/openfe/wiki/How-to-create-a-new-release)
```
This?

2024-11-12 21:23 UTC, atravitz commented on .github/PULL_REQUEST_TEMPLATE/release_template.md
> +After Merging the PR [follow this guide]https://github.com/OpenFreeEnergy/openfe/releases/new
🤦yes.

2024-11-12 22:31 UTC, IAlibay approved these changes
lgtm!

2024-11-12 22:38 UTC, merged