create test data for quickrun submitted in parallel
OpenFreeEnergy/openfe pull request #1040
Opened 2024-12-06 17:46 UTC by atravitz

- **add docstrings**
- **adding code for creating parallel directory**
- **updating nb**
- **adding zipped test data**
- **updating script for mocking up parallel test data**

Checklist
* [ ] Added a ``news`` entry

## Developers certificate of origin
- [ ] I certify that this contribution is covered by the MIT License [here](https://github.com/OpenFreeEnergy/openfe/blob/main/LICENSE) and the **Developer Certificate of Origin** at <https://developercertificate.org/>.

2024-12-06 18:27 UTC, atravitz commented on openfecli/tests/commands/test_gather.py
> +def results_dir_parallel(tmpdir):
I don't actually use this fixture in this PR, since I just want to add the test data here and not add any tests that would fail.

2024-12-06 19:10 UTC, IAlibay commented
@atravitz can you confirm that you loaded these back into ProtocolResults objects and it reads fine?

2024-12-09 11:53 UTC, IAlibay requested changes
Just the one thing, otherwise - if it loads back up properly - then it looks good to me.

2024-12-09 11:53 UTC, IAlibay commented on openfecli/tests/data/restructure_results_data.ipynb
> +    "                          'uncertainty': 0.0,\n",
uncertainty should be an openff.unit.Quantity (compatible with kcal/mol)

2024-12-09 16:11 UTC, jthorton approved these changes
LGTM!

2024-12-09 16:40 UTC, atravitz commented
> @atravitz can you confirm that you loaded these back into ProtocolResults objects and it reads fine?

Both the `protocol_result` and `unit_results` load correctly

2024-12-09 16:51 UTC, merged