Codeowners
OpenFreeEnergy/openfe pull request #259
Opened 2023-02-14 16:06 UTC by dwhswenson

This PR adds a CODEOWNERS file. If you are one of the owners of a given file, this will mean that you will be automatically requested to review any changes of that file.

Purposes here are:

1. Use GitHub's CODEOWNERS support to automatically request reviews
2. Provide an easy mechanism to identify who should be asked if there's a question about a particular piece of code
3. Provide a way to re-assign those responsibilities if someone leaves the team. 

Assignments here are provisional; everyone please look over them, and suggest changes as you wish. Also, we can have multiple owners per path, although I've only assigned one person so far, so if you want to double up with someone, let me know.

The file maps paths to owners; from this you can get the mapping of owners to paths. This is useful if someone leaves the project; we can re-assign their paths. Here's a little code to getter the reverse mapping (and its output, so you all can see what your provisional assignments are).

```python
In [1]: # python -m pip install codeowners
   ...: import codeowners
   ...: with open("CODEOWNERS") as f:
   ...:     owners_txt = f.read()
   ...:

In [2]: owners = codeowners.CodeOwners(owners_txt)

In [3]: def paths_for_owner(owner, codeowners, sole_ownership=False):
   ...:     for (pattern, pattern_str, owners, lineno, sec) in codeowners.paths:
   ...:         for ownertype, ownername in owners:
   ...:             if ownername == owner:
   ...:                 if sole_ownership and len(owners) == 1:
   ...:                     yield pattern_str
   ...:                 elif not sole_ownership:
   ...:                     yield pattern_str
   ...:

In [4]: list(paths_for_owner("@dwhswenson", owners))
Out[4]:
['openfecli/*',
 'openfe/**/utils/*custom_typing.py',
 'openfe/**/utils/*network_plotting.py',
 'openfe/tests/dev/*',
 'openfe/**/setup/*ligand_network*',
 'openfe/**/setup/atom_mapping/*ligandatommapper.py',
 'readthedocs.yml',
 'docs/*',
 'CODEOWNERS',
 'setup.*',
 '.git*',
 '.coveragerc']

In [5]: list(paths_for_owner("@richardjgowers", owners))
Out[5]:
['openfe/tests/**/conftest.py',
 'openfe/tests/data/*',
 'openfe/**/setup/atom_mapping/*lomap*',
 'openfe/tests/setup/test_openmm_equil_protocols.py',
 'openfe/**/protocols/openmm_rbfe/*equil_rbfe_methods.py',
 'openfe/protocols/openm_rbfe/__init__.py',
 'openfe/**/__init__.py',
 'README.md',
 'LICENSE']

In [6]: list(paths_for_owner("@IAlibay", owners))
Out[6]: ['openfe/**/protocols/openmm_rbfe/_rbfe_utils/*', 'environment.yml']

In [7]: list(paths_for_owner("@riesben", owners))
Out[7]:
['openfe/**/utils/*optional_imports.py',
 'openfe/**/utils/*visualization_3D.py',
 'openfe/**/setup/atom_mapping/*perses*']

In [8]: list(paths_for_owner("@mikemhenry", owners))
Out[8]: ['versioneer.py', 'devtools/*', 'MANIFEST.in', 'CITATION.cff']
```

Also, we can check which files do not have an owner (there's probably a GH Action for this somewhere, but it was as easy to write my own code for it):

```python
In [9]: all_files = !git ls-tree -r --name-only HEAD

In [10]: for file in all_files:
    ...:     file_owners = owners.of(file)
    ...:     if not file_owners:
    ...:         print(file)
    ...:
.readthedocs.yaml
```

The only thing that is currently missing an owner is the `.readthedocs.yaml` file, which is being removed in #258.

Adding CI to check that every file has an owner, and that every owner path matches at least one file, should be done in a future PR.

FWIW, provisional codeowners were determined from the output of

```
git ls-tree -r -z --name-only HEAD -- $file | 
xargs -0 -n1 git blame --line-porcelain HEAD |
grep  "^author " | sort | uniq -c | sort -nr
```

for each file, combined with some background knowledge on who worked on what (Richard has git blame for `_rbfe_utils`, but that's because he copied it from Irfan).

2023-02-15 17:29 UTC, dwhswenson commented
A few points:

* To clarify the role: Although the file is called CODEOWNERS, the responsibilities I'm suggesting are more along the lines of "code stewardship" (or "very weak ownership.") As a single place to start reading on these distinctions, [this gives a good overview with lots of links to other writing](https://dzone.com/articles/code-ownership-–-who-should).
* To clarify review: It would be good if ***everyone*** reviewed this, mainly to look at the paths you're assigned (see the IPython session in the main post).
* There is a [GitHub action to validate CODEOWNERS](https://github.com/mszostok/codeowners-validator/blob/main/docs/gh-action.md) (documenting it here so I don't have to keep that tab open forever.) Incorporating that into CI that would come in a future PR.

2023-02-27 08:57 UTC, RiesBen approved these changes

2023-02-27 17:50 UTC, mikemhenry approved these changes

2023-04-13 10:21 UTC, SauravMaheshkar requested changes

2023-04-13 10:21 UTC, SauravMaheshkar commented on CODEOWNERS
I'd suggest moving this file to within the `.github/` directory. It'll still function the same but as it is a Github specific file I think it makes more sense for it to be within the `.github/` directory.

2024-01-30 12:55 UTC, closed without merging