Don't exclude py3.10 macos runners
OpenFreeEnergy/openfe pull request #319
Opened 2023-04-07 10:10 UTC by IAlibay

With OpenMM 8 out, this should be ok to do now.

2023-04-10 13:28 UTC, richardjgowers requested changes
macos is already the slowest runner, we don't need to test both py3.9 and py3.10

2023-04-10 13:30 UTC, IAlibay commented
> macos is already the slowest runner, we don't need to test both py3.9 and py3.10

did we fix things on arm64-osx? we could use the cirrus runners, they are blazing fast

2023-04-10 16:39 UTC, IAlibay commented
Should be good for re-review @richardjgowers - just bumped the runner to 3.10 is all.

Once merged we'll need to cycle the "required checks" in the repo settings.

2023-04-11 21:46 UTC, richardjgowers approved these changes

2023-04-12 10:15 UTC, merged