[WIP] DOCS: Cleanup guide intro
OpenFreeEnergy/openfe pull request #341
Opened 2023-04-12 17:30 UTC by dwhswenson

- [x] Add gather CLI command page
- [x] Add command examples on intro page
- [ ] Link to tutorial on making SLURM jobs
- [ ] Add figures for workflows

2023-04-12 20:16 UTC, IAlibay requested changes

2023-04-12 20:16 UTC, IAlibay commented on docs/guide/introduction.rst
> +For example, you can create an RBFE network using
RBFE -> Relative Binding Free Energy (RBFE) first use of a the acronym in this document right?

2023-04-12 20:16 UTC, IAlibay commented on docs/guide/introduction.rst
>  edge of the :class:`.AlchemicalNetwork` (i.e., each leg of the simulation).
```suggestion
edge of the :class:`.AlchemicalNetwork` (i.e., each leg of the alchemical cycle).
```

I think this is what you're trying to say here?

2023-04-18 07:46 UTC, IAlibay commented
Just added a minimum sentence structure fix ahed of @richardjgowers' possible great merge

2023-05-06 23:58 UTC, IAlibay commented
@dwhswenson if you don't mind I'll take over here and address the review comments I made & merge eagerly so we can have semi sensical docs for this week

2023-05-06 23:59 UTC, dwhswenson commented
Please do! I've been distracted in other directions.

2023-05-08 10:18 UTC, richardjgowers approved these changes

2023-05-08 10:21 UTC, merged