[wip] Plan rbfe network radial
OpenFreeEnergy/openfe pull request #488
Opened 2023-07-13 13:33 UTC by richardjgowers

2023-07-18 17:08 UTC, dwhswenson requested changes
I'm still not a fan of this special treatment of star maps. I think the better solution is either `plan-rbfe-starmap` or a more generic approach based on our plugin infrastructure. But since we won't make the time to do that, I've got some suggestions on improving this.

2023-07-19 10:46 UTC, richardjgowers commented on openfecli/plan_alchemical_networks_utils.py
> +    for filename in sorted(filenames):
it's annoying when these are unsorted as it's harder to read/check what's been produced, I can sort as we get them out of the network

2023-07-19 10:46 UTC, richardjgowers commented on openfecli/commands/plan_rbfe_network.py
> +    if radial:
I raise a warning now, is there a proper way to do this through click?

2023-07-19 14:57 UTC, RiesBen requested changes
I like this addition to the CLI tools here! :) Only have one comment on the PR.

2023-07-19 14:57 UTC, RiesBen commented on openfecli/commands/plan_rbfe_network.py
> +)
Could make sense, to implement these options in parameters and only import them here.

like MOL_DIR, that way you could share the implementation for rhfes an rbfes  and both clis have the same guaranteed cli experience.

2023-07-19 14:57 UTC, RiesBen commented on openfecli/commands/plan_rhfe_network.py
> +)
see above

2023-07-19 14:57 UTC, RiesBen commented on openfecli/utils.py
> +    ligand_network_planner = partial(generate_radial_network,
oh cool I  did not know about partial :) But I like it! :)

2023-11-03 09:19 UTC, richardjgowers commented
Probably superseded by #583 and #592

2023-11-21 19:33 UTC, richardjgowers commented
-

2023-11-21 19:33 UTC, closed without merging