Add devtools for json results generation + replace old ones
OpenFreeEnergy/openfe pull request #691
Opened 2024-01-25 16:15 UTC by IAlibay

Fixes #685

Adds a Python script with quickrun-like serialization behaviour so we can re-generate the results files in a consistent manner.

## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT License [here](https://github.com/OpenFreeEnergy/openfe/blob/main/LICENSE) and the **Developer Certificate of Origin** at <https://developercertificate.org/>.

2024-01-25 16:16 UTC, pep8speaks commented
Hello @IAlibay! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`devtools/data/gen-serialized-results.py`](https://github.com/OpenFreeEnergy/openfe/blob/f35ac58e15af861652300c4058dda78e1780b7a8/devtools/data/gen-serialized-results.py):

> [Line 60:80](https://github.com/OpenFreeEnergy/openfe/blob/f35ac58e15af861652300c4058dda78e1780b7a8/devtools/data/gen-serialized-results.py#L60): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 73:80](https://github.com/OpenFreeEnergy/openfe/blob/f35ac58e15af861652300c4058dda78e1780b7a8/devtools/data/gen-serialized-results.py#L73): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 74:80](https://github.com/OpenFreeEnergy/openfe/blob/f35ac58e15af861652300c4058dda78e1780b7a8/devtools/data/gen-serialized-results.py#L74): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 75:80](https://github.com/OpenFreeEnergy/openfe/blob/f35ac58e15af861652300c4058dda78e1780b7a8/devtools/data/gen-serialized-results.py#L75): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 76:80](https://github.com/OpenFreeEnergy/openfe/blob/f35ac58e15af861652300c4058dda78e1780b7a8/devtools/data/gen-serialized-results.py#L76): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 81:80](https://github.com/OpenFreeEnergy/openfe/blob/f35ac58e15af861652300c4058dda78e1780b7a8/devtools/data/gen-serialized-results.py#L81): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 79 characters)
> [Line 117:1](https://github.com/OpenFreeEnergy/openfe/blob/f35ac58e15af861652300c4058dda78e1780b7a8/devtools/data/gen-serialized-results.py#L117): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

* In the file [`openfe/tests/protocols/conftest.py`](https://github.com/OpenFreeEnergy/openfe/blob/f35ac58e15af861652300c4058dda78e1780b7a8/openfe/tests/protocols/conftest.py):

> [Line 201:80](https://github.com/OpenFreeEnergy/openfe/blob/f35ac58e15af861652300c4058dda78e1780b7a8/openfe/tests/protocols/conftest.py#L201): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)

2024-01-26 14:08 UTC, richardjgowers requested changes
the 3 `.gz` files in devtools/data are the same as the test data files right?  So can I remove the 3 devtools/data copies?

2024-01-26 18:10 UTC, IAlibay commented
> the 3 `.gz` files in devtools/data are the same as the test data files right? So can I remove the 3 devtools/data copies?

Ah my bad, forgot about those - fixed

2024-01-29 10:36 UTC, richardjgowers approved these changes

2024-01-29 10:37 UTC, merged